config/routes.rb
Rails.application.routes.draw do
  root "videos#index"
  resources :sessions, only: [:create, :destroy]
  resources :videos, only: [:index, :new, :create]
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :videos

  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  YOUTUBE_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  validates :link, presence: true, format: YOUTUBE_LINK_FORMAT
  before_save :get_information

  private
  def get_information
    video = Yt::Video.new url: self.link
    self.uid = video.id
    self.title = video.title
    self.description = video.description
    self.likes = video.like_count
    self.dislikes = video.dislike_count
    self.published_at = video.published_at
  rescue Yt::Errors::NoItems
    raise
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if not user
      user = User.create(email: params[:email], password: params[:password])
    end
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in sucessfully!"
    else
      redirect_to root_url, alert: "Password is invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out sucessfully!"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :check_authentication, only: [:new, :create]

  def new
    @video = Video.new
  end

  def index
    @videos = Video.order("created_at DESC")
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    begin
      if @video.save
        flash[:success] = "Share movie successfully"
        redirect_to root_url
      else
        flash.now[:alert] = "Youtube video URL is invalid"
        render :new
      end
    rescue
      flash.now[:alert] = "Youtube video is not found"
      render :new
    end
  end

  private
  def video_params
    params.require(:video).permit(:link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def check_authentication
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemitanoTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">
          <i class="fa fa-home" aria-hidden="true"></i> Funny Movie
        </a>
        <% if current_user %>
          <div class="form-inline">
            <span class="navbar-text mr-sm-2">
              Welcome <%= current_user.email %>
            </span>
            <%= link_to "Share a movie", new_video_path, class: "btn btn-success mr-sm-2" %>
            <%= link_to "Log Out", logout_path, class: "btn btn-warning mr-sm-2" %>
          </div>
        <% else %>
          <%= form_tag sessions_path, class: "form-inline" do |form| %>
            <%= text_field_tag :email, "", class: "form-control mr-sm-2", placeholder: "Email" %>
            <%= password_field_tag :password, "", class: "form-control mr-sm-2", placeholder: "Password" %>
            <%= submit_tag "Login / Register", class: "btn btn-primary my-2 my-sm-0" %>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="container py-md-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/index.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if @videos.any? %>
  <% @videos.each do |video| %>
    <div class="row">
      <% if video %>
        <div class="col-md-4">
          <div class="thumbnail">
            <%= link_to image_tag(
              "https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg",
              alt: video.title,
              class: "img-rounded img-fluid"),
              "https://www.youtube.com/watch?v=#{video.uid}", target: "_blank" %>
          </div>
        </div>
        <div class="col-md-8">
          <div class="caption">
            <h5><%= video.title %></h5>
            <p>Shared by <%= video.user.email %></p>
            <p>
            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> <%= video.likes %>
          <i class="fa fa-thumbs-o-down" aria-hidden="true"></i> <%= video.dislikes %>
            </p>
            <p><%= video.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/videos/new.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>
<div class="row justify-content-md-center">
  <div class="col-sm-8">
    <div class="card">
      <div class="card-body">
        <h6 class="card-subtitle text-muted">
          Share a youtube movie
        </h6>
        <%= form_for @video do |f| %>
          <div class="form-group row">
            <div class="col-sm-3">
              <%= f.label :link, "Youtube URL" %>
            </div>
            <div class="col-sm-9">
              <%= f.text_field :link, class: "form-control", required: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-9 offset-sm-3">
              <%= f.submit "Share", class: "btn btn-primary btn-block" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>